export const BREEZEWAY_TEAM_MAP: Record<string, string> = {
  INCLUDED: process.env.BREEZEWAY_CONCIERGE_TEAM_ID || '',
  ARRIVAL_TRANSIT: process.env.BREEZEWAY_CONCIERGE_TEAM_ID || '',
  WELLNESS: process.env.BREEZEWAY_WELLNESS_TEAM_ID || '',
  CULINARY_AGAVE: process.env.BREEZEWAY_CULINARY_TEAM_ID || '',
  OCEAN_ADVENTURE: process.env.BREEZEWAY_CONCIERGE_TEAM_ID || '',
  EXCURSIONS: process.env.BREEZEWAY_CONCIERGE_TEAM_ID || '',
  PRIVATE: process.env.BREEZEWAY_CONCIERGE_TEAM_ID || '',
};

export const EXPERIENCE_LEAD_TIMES: Record<string, number> = {
  INCLUDED: 30,
  ARRIVAL_TRANSIT: 120,
  WELLNESS: 60,
  CULINARY_AGAVE: 180,
  OCEAN_ADVENTURE: 45,
  EXCURSIONS: 240,
  PRIVATE: 60,
};
