import type { ApprovalQueueItem } from '@/types';

export const conflictDetectedMessage =
  "Chef's Table requested by J. Makarov (Villa 3) at 7:00 PM overlaps with a confirmed pool catering booking. Resolution required before approval.";

export const approvalQueueItems: ApprovalQueueItem[] = [
  {
    id: 'aq1',
    guestName: 'J. Makarov',
    initials: 'JM',
    partyLabel: 'Villa 3 · Party of 2',
    experience: "Chef's Table",
    experienceDetail: 'Oceanfront · 4-course',
    villa: 'Villa 3',
    requestedDate: 'Mar 27',
    requestedTime: '7:00 PM',
    vendor: 'Cocina del Mar',
    submitted: '2h ago',
    status: 'Conflict',
  },
  {
    id: 'aq2',
    guestName: 'A. Khalil',
    initials: 'AK',
    partyLabel: 'Villa 1 · Party of 4',
    experience: 'Private Surf Lesson',
    experienceDetail: 'Beach South · 2 hrs',
    villa: 'Villa 1',
    requestedDate: 'Mar 27',
    requestedTime: '2:00 PM',
    vendor: 'Azure Charters',
    submitted: '2h ago',
    status: 'Pending',
  },
  {
    id: 'aq3',
    guestName: 'Martinez Family',
    initials: 'MF',
    partyLabel: 'Villa 4 · Party of 6',
    experience: 'Sunset Yacht Dinner',
    experienceDetail: 'Full crew · Open bar',
    villa: 'Villa 4',
    requestedDate: 'Mar 28',
    requestedTime: '6:30 PM',
    vendor: 'Azure Charters',
    submitted: '45m ago',
    status: 'Pending',
  },
  {
    id: 'aq4',
    guestName: 'R. Lindqvist',
    initials: 'RL',
    partyLabel: 'Villa 6 · Party of 3',
    experience: 'Helicopter Tour',
    experienceDetail: 'Coastal route · 90 min',
    villa: 'Villa 6',
    requestedDate: 'Mar 28',
    requestedTime: '10:00 AM',
    vendor: 'SkyLine Tours',
    submitted: '1h ago',
    status: 'Pending',
  },
  {
    id: 'aq5',
    guestName: 'S. Okafor',
    initials: 'SO',
    partyLabel: 'Villa 4 · Party of 2',
    experience: 'In-Villa Spa',
    experienceDetail: 'Couples package',
    villa: 'Villa 4',
    requestedDate: 'Mar 27',
    requestedTime: '12:00 PM',
    vendor: 'Serenity Spa',
    submitted: '3h ago',
    status: 'Confirmed',
  },
  {
    id: 'aq6',
    guestName: 'A. Khalil',
    initials: 'AK',
    partyLabel: 'Villa 1 · Party of 4',
    experience: 'Private Chef Dinner',
    experienceDetail: 'Villa terrace',
    villa: 'Villa 1',
    requestedDate: 'Mar 26',
    requestedTime: '7:30 PM',
    vendor: 'Culinary Co.',
    submitted: 'Yesterday',
    status: 'In Progress',
  },
  {
    id: 'aq7',
    guestName: 'R. Lindqvist',
    initials: 'RL',
    partyLabel: 'Villa 6 · Party of 3',
    experience: 'Wine Tasting',
    experienceDetail: 'Estate cellar',
    villa: 'Villa 6',
    requestedDate: 'Mar 25',
    requestedTime: '5:00 PM',
    vendor: 'Estate Cellar',
    submitted: '2 days ago',
    status: 'Completed',
  },
  {
    id: 'aq8',
    guestName: 'Martinez Family',
    initials: 'MF',
    partyLabel: 'Villa 4 · Party of 6',
    experience: 'Helicopter Tour',
    experienceDetail: 'Sunset slot',
    villa: 'Villa 4',
    requestedDate: 'Mar 24',
    requestedTime: '4:00 PM',
    vendor: 'SkyLine Tours',
    submitted: '3 days ago',
    status: 'Declined',
  },
];
