import type { VendorProfile } from '@/types';

export const vendorProfiles: VendorProfile[] = [
  {
    id: 'v-cocina',
    name: 'Cocina del Mar',
    category: 'culinary',
    categoryLabel: 'Culinary',
    rating: 5,
    lead: 'Rodrigo Solis',
    location: 'Puerto Escondido',
    description:
      'Award-winning coastal cuisine with estate-trained chefs. Specialises in ocean-to-table dining and private villa experiences.',
    serviceTags: ["Chef's Table", 'Private Dining', 'Wine Pairing'],
    totalBookings: 28,
    avgRating: 4.9,
    avgBooking: '$4.2k',
  },
  {
    id: 'v-tierra',
    name: 'Tierra Spa',
    category: 'wellness',
    categoryLabel: 'Wellness',
    rating: 5,
    lead: 'Sofia Lindqvist',
    location: 'On-site Estate',
    description:
      'Full-service wellness partner offering in-villa massage, holistic treatments, and bespoke spa programmes for guests.',
    serviceTags: ['Massage', 'Couples Treatment', 'Wellness Ritual'],
    totalBookings: 62,
    avgRating: 4.8,
    avgBooking: '$680',
  },
  {
    id: 'v-surf',
    name: 'Punta Surf School',
    category: 'water-sports',
    categoryLabel: 'Water Sports',
    rating: 4,
    lead: 'Diego Herrera',
    location: 'Playa Punta',
    description:
      'Premier surf instruction and equipment for all levels. Private lessons, group sessions, and board hire available daily.',
    serviceTags: ['Private Lesson', 'Group Session', 'Board Hire'],
    totalBookings: 34,
    avgRating: 4.7,
    avgBooking: '$320',
  },
  {
    id: 'v-yacht',
    name: 'Pacifico Yachts',
    category: 'marine',
    categoryLabel: 'Marine',
    rating: 5,
    lead: 'Marco Valenti',
    location: 'Marina Bay',
    description:
      'Luxury yacht charters for sunset cruises, day trips, and private celebrations along the Pacific coast.',
    serviceTags: ['Yacht Charter', 'Sunset Cruise', 'Private Event'],
    totalBookings: 29,
    avgRating: 4.9,
    avgBooking: '$4.8k',
  },
  {
    id: 'v-sommelier',
    name: 'Estate Sommelier',
    category: 'wellness',
    categoryLabel: 'Wellness',
    rating: 5,
    lead: 'Elena Vasquez',
    location: 'Estate Cellar',
    description:
      'Curated wine experiences including cellar tastings, pairing dinners, and private sommelier sessions for villa guests.',
    serviceTags: ['Wine Tasting', 'Cellar Tour', 'Pairing Dinner'],
    totalBookings: 41,
    avgRating: 5.0,
    avgBooking: '$890',
  },
];
